project:
  type: website
  output-dir: docs
  resources:
    - images/

book:
  title: "CASA0025 Final Assessment"
  author: "SQLitos: Emily Deeb, Santiago Soubie, Nadia Cabrera Salazar, Tabata Paredes Condor and Chad Barrett"
  date: "2026-04-24"
  chapters:
    - index.qmd
  repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  favicon: favicon.ico
  sidebar:
    logo: casa_logo.png

format:
  html:
    theme:
      dark: darkly
      light: cosmo
    code-copy: true
    code-overflow: wrap
    highlight-style: monokai.theme
    linkcolor: "#34a832"


