project:
  type: website
  output-dir: docs
  resources:
    - images/

website:
  title: "CASA0025 Final Assessment"
  favicon: favicon.ico
  repo-url: https://github.com/chad-casa/0025_BSA-Group
  repo-actions: [edit]
  navbar:
    right:
      - icon: github
        href: "https://github.com/EmilyDeeb/0025_BSA-Group"
  # sidebar:
  #   logo: casa_logo.png

format:
  html:
    theme:
      dark: darkly
      light: cosmo
    code-copy: true
    code-overflow: wrap
    linkcolor: "#34a832"
    # highlight-style: monokai.theme
